import { SiteFooter } from "@/components/site-footer";
import { ProfileNav } from "@/components/profile-nav";

export default function TermsPage() {
  return <main className="shell legal-page">
    <ProfileNav variant="standard" />
    <article className="legal-card">
      <div className="legal-copy de-copy"><div className="eyebrow">Rechtliches</div><h1>Allgemeine Geschäftsbedingungen</h1><p className="note">für AI Music Rebels · Stand: 02.09.2026</p><p>Anbieter: Michael Jobst, Waldweg 3, 91171 Greding, Deutschland · jobst67@gmail.com · 0160 4589605</p>
      <h2>1. Geltungsbereich</h2><p>Diese AGB gelten für die Nutzung von AI Music Rebels und für den Abschluss eines kostenpflichtigen Jahresabonnements für eine Künstlerseite. Das Angebot richtet sich in dieser Fassung an volljährige Kunden mit Wohnsitz, gewöhnlichem Aufenthalt oder Unternehmenssitz in Deutschland. Abweichende Bedingungen des Kunden werden nur Vertragsbestandteil, wenn wir ihrer Geltung ausdrücklich zustimmen.</p>
      <h2>2. Leistungsbeschreibung</h2><p>AI Music Rebels stellt eine persönliche Künstlerseite unter einer Subdomain von aimusicrebels.com bereit. Nutzer können Profilbild, Banner, Beschreibung, Links sowie Verweise auf eigene Titel und Videos hinterlegen. Das Angebot produziert, vertreibt oder lizenziert keine Musik und übernimmt keine Rechteklärung für vom Nutzer verlinkte Inhalte oder Dienste Dritter.</p>
      <h2>3. Nutzerkonto und Inhalte</h2><p>Für die Reservierung einer Subdomain ist ein bestätigtes Nutzerkonto erforderlich. Zugangsdaten sind geheim zu halten. Nutzer sind für die Rechtmäßigkeit, Richtigkeit und die erforderlichen Rechte an ihren Profilinhalten, Bildern, Titeln, Videos und externen Links verantwortlich. Rechtswidrige, verletzende oder missbräuchliche Inhalte dürfen nicht eingestellt werden.</p>
      <h2>4. Laufzeit, Testmonat und Preis</h2><p>Der Kanalzugang beginnt mit einem kostenlosen Testzeitraum von 30 Tagen. Anschließend beträgt der Preis 9,99 EUR pro Jahr, sofern beim Checkout nicht ein anderer Endpreis angezeigt wird. Die Zahlungsdaten werden über Stripe verarbeitet. Michael Jobst ist Kleinunternehmer im Sinne des § 19 UStG; es wird keine Umsatzsteuer erhoben.</p>
      <h2>5. Kündigung und Basisprofil</h2><p>Das Abonnement kann über den Stripe-Kundenbereich im Account gekündigt werden. Nach Ende eines nicht verlängerten oder nicht bezahlten Abonnements wird die Seite auf ein Basisprofil zurückgesetzt: Banner, Bild, Bio und Links bleiben gespeichert; Titel, Videos und interne Vorschauen sind nicht mehr öffentlich verfügbar. Eine erneute Aktivierung ist möglich. Optionale Erinnerungen zur Reaktivierung werden höchstens monatlich versendet und können im Account abgewählt werden.</p>
      <h2>6. Sperrung</h2><p>Wir können den Zugang vorübergehend sperren und öffentliche Profile ausblenden, wenn konkrete Anhaltspunkte für einen Verstoß gegen diese AGB, geltendes Recht oder Rechte Dritter bestehen. Soweit zumutbar, informieren wir vorher oder unverzüglich danach über die Maßnahme und den Grund.</p>
      <h2>7. Verfügbarkeit und Haftung</h2><p>Wir bemühen uns um eine möglichst störungsfreie Verfügbarkeit, schulden aber keine ununterbrochene Verfügbarkeit. Bei leichter Fahrlässigkeit haften wir nur bei Verletzung wesentlicher Vertragspflichten und begrenzt auf den vorhersehbaren, vertragstypischen Schaden. Unberührt bleiben Ansprüche wegen Vorsatz, grober Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit sowie nach zwingendem Recht.</p>
      <h2>8. Änderungen</h2><p>Wir können diese AGB ändern, wenn hierfür ein sachlicher Grund besteht und die Änderung zumutbar ist. Über wesentliche Änderungen informieren wir rechtzeitig in Textform.</p>
      <h2>9. Schlussbestimmungen</h2><p>Es gilt deutsches Recht. Die gesetzlichen Rechte von Verbrauchern bleiben unberührt.</p></div>
      <div className="legal-copy en-copy"><div className="eyebrow">Legal</div><h1>Terms and Conditions</h1><p className="note">for AI Music Rebels · effective 2 September 2026</p><p>Provider: Michael Jobst, Waldweg 3, 91171 Greding, Germany · jobst67@gmail.com · +49 160 4589605</p>
      <h2>1. Scope</h2><p>These terms apply to AI Music Rebels and to annual subscriptions for artist pages. This version is aimed at adults residing or established in Germany. Deviating terms apply only if expressly accepted by us.</p>
      <h2>2. Service</h2><p>AI Music Rebels provides a personal artist page under a subdomain of aimusicrebels.com. Users can add an image, banner, biography, links and references to their own tracks and videos. We do not create, distribute or license music and do not clear rights for user content or third-party services.</p>
      <h2>3. Account and content</h2><p>A verified account is required. Users must keep access credentials secret and are responsible for the legality and necessary rights for all profile content, images, tracks, videos and external links.</p>
      <h2>4. Trial, price and billing</h2><p>Channel access begins with a 30-day free trial. Afterwards the price is EUR 9.99 per year unless a different final price is shown at checkout. Payments are processed by Stripe. As a small business under section 19 UStG, no VAT is charged.</p>
      <h2>5. Cancellation and basic profile</h2><p>Subscriptions can be cancelled through the Stripe customer portal. At the end of an unpaid or non-renewed subscription, the page becomes a basic profile: banner, image, biography and links remain stored, while tracks, videos and internal previews are no longer public. Reactivation is possible. Optional reactivation reminders are sent no more than monthly and can be disabled in the account.</p>
      <h2>6. Suspension</h2><p>We may temporarily suspend access and hide public profiles where there are concrete indications of a breach of these terms, law or third-party rights. Where reasonable, we will inform the user before or immediately after the measure.</p>
      <h2>7. Availability and liability</h2><p>We strive for reliable availability but do not guarantee uninterrupted operation. For ordinary negligence, liability is limited to breaches of material contractual obligations and foreseeable typical damage. Mandatory statutory liability remains unaffected.</p>
      <h2>8. Final provisions</h2><p>German law applies. Mandatory consumer rights remain unaffected.</p></div>
    </article><SiteFooter />
  </main>;
}
