"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { SiteFooter } from "@/components/site-footer";
import { ProfileNav } from "@/components/profile-nav";

function normalizeSlug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,32)}

export default function ClaimSubdomainPage(){
 const [artistName,setArtistName]=useState(""); const [slugInput,setSlugInput]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const slug=useMemo(()=>normalizeSlug(slugInput||artistName),[slugInput,artistName]);
 useEffect(()=>{void (async()=>{const s=getSupabase(); const {data}=await s.auth.getUser(); if(!data.user){window.location.replace("/login?next=/claim-subdomain");return} const {data:p}=await s.from("artist_profiles").select("id").eq("user_id",data.user.id).maybeSingle(); if(p) window.location.replace("/account")})()},[]);
 async function claim(e:FormEvent){e.preventDefault();if(slug.length<3){setMessage("Please choose at least 3 characters.");return}setBusy(true);setMessage("");try{const s=getSupabase();const {data:u}=await s.auth.getUser();if(!u.user)throw new Error("Please sign in again.");if(u.user.email&&!u.user.email_confirmed_at){setMessage("Bitte bestätige zuerst deine E-Mail-Adresse.");return}const {data:available,error:aerr}=await s.rpc("is_subdomain_available",{requested_slug:slug});if(aerr)throw aerr;if(!available){setMessage("This subdomain is already taken.");return}const {data:r,error:rerr}=await s.from("subdomain_reservations").insert({slug,user_id:u.user.id,status:"pending"}).select("id").single();if(rerr)throw rerr;const start=new Date(),end=new Date(start.getTime()+30*24*60*60*1000);const {error:perr}=await s.from("artist_profiles").insert({user_id:u.user.id,reservation_id:r.id,slug,artist_name:artistName||slug,is_published:false,billing_status:"trialing",channel_mode:"full",trial_started_at:start.toISOString(),trial_ends_at:end.toISOString(),winback_opt_in:true});if(perr)throw perr;try{const {data:sessionData}=await s.auth.getSession();await fetch("/api/notifications/registration",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+(sessionData.session?.access_token??"")},body:JSON.stringify({profileId:r.id})})}catch(notificationError){console.error("Registration notification failed",notificationError)}window.location.assign("/account")}catch(err){setMessage(err instanceof Error?err.message:"Could not claim subdomain.")}finally{setBusy(false)}}
 return <main className="shell page"><ProfileNav variant="standard" /><section className="profile" style={{maxWidth:620,margin:"0 auto",paddingTop:70}}><div className="eyebrow">STEP 2</div><h1 className="hero-title">Claim your Subdomain.</h1><p className="lead">Your own address on AI Music Rebels. Choose it once, then build your artist profile.</p><div className="card"><form className="form" onSubmit={claim}><div><label>Artist name</label><input value={artistName} onChange={e=>setArtistName(e.target.value)} placeholder="Voitto Tai Kooma" required /></div><div><label>Your subdomain</label><input value={slugInput} onChange={e=>setSlugInput(e.target.value)} placeholder={slug||"your-artist-name"}/><p className="note">{slug||"your-artist-name"}.aimusicrebels.com</p></div><button disabled={busy}>{busy?"Checking …":"Claim this subdomain"}</button>{message&&<p className="note error">{message}</p>}</form></div></section><SiteFooter/></main>
}
