"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { getSupabase, hasSupabaseConfig } from "@/lib/supabase";
import { SiteFooter } from "@/components/site-footer";

const publicSiteUrl=(process.env.NEXT_PUBLIC_APP_URL??"https://aimusicrebels.com").replace(/\/$/,"");
export default function AuthPage(){
 const [mode,setMode]=useState<"login"|"signup">("signup");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const nextPath=()=>new URLSearchParams(window.location.search).get("next")||"/claim-subdomain";
 useEffect(()=>{const s=getSupabase();const finish=()=>window.location.replace(nextPath());const {data:l}=s.auth.onAuthStateChange((event,session)=>{if((event==="SIGNED_IN"||event==="INITIAL_SESSION")&&session)finish()});s.auth.getSession().then(({data})=>{if(data.session)finish()});return()=>l.subscription.unsubscribe()},[]);
 function redirectUrl(){return `${publicSiteUrl}/auth?next=${encodeURIComponent(nextPath())}`}
 async function google(){setBusy(true);setMessage("");try{if(!hasSupabaseConfig)throw new Error("Login is being configured.");const {error}=await getSupabase().auth.signInWithOAuth({provider:"google",options:{redirectTo:redirectUrl()}});if(error)throw error}catch(e){setMessage(e instanceof Error?e.message:"Google login failed.");setBusy(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{if(!hasSupabaseConfig)throw new Error("Die Anmeldung wird gerade eingerichtet.");const s=getSupabase();if(mode==="signup"){const {error}=await s.auth.signUp({email,password,options:{emailRedirectTo:redirectUrl()}});if(error)throw error;setMessage("Bitte bestätige deine E-Mail-Adresse. Danach geht es direkt zu Claim your Subdomain.")}else{const {error}=await s.auth.signInWithPassword({email,password});if(error)throw error;window.location.href=nextPath()}}catch(e){setMessage(e instanceof Error?e.message:"Anmeldung fehlgeschlagen.")}finally{setBusy(false)}}
 async function resend(){if(!email){setMessage("Trage zuerst deine E-Mail-Adresse ein.");return}setBusy(true);try{const {error}=await getSupabase().auth.resend({type:"signup",email,options:{emailRedirectTo:redirectUrl()}});if(error)throw error;setMessage("Neue Bestätigungs-E-Mail wurde gesendet.")}catch(e){setMessage(e instanceof Error?e.message:"E-Mail konnte nicht gesendet werden.")}finally{setBusy(false)}}
 return <main className="shell auth"><Link className="brand" href="/">AI MUSIC <em>REBELS</em></Link><section className="card"><h2>{mode==="signup"?"Join the rebellion.":"Willkommen zurück."}</h2><p>Erst registrieren. Danach sicherst du dir deine kostenlose Subdomain.</p><button type="button" onClick={google} disabled={busy} style={{width:"100%",margin:"12px 0 18px"}}>G &nbsp; Continue with Google</button><div style={{display:"flex",alignItems:"center",gap:10,color:"#777",fontSize:12}}><span style={{height:1,background:"#444",flex:1}}/><b>ODER</b><span style={{height:1,background:"#444",flex:1}}/></div><div className="switch" style={{marginTop:18}}><button type="button" className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Registrieren</button><button type="button" className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Anmelden</button></div><form className="form" onSubmit={submit}><div><label>E-Mail</label><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div><label>Passwort</label><input type="password" minLength={8} autoComplete={mode==="signup"?"new-password":"current-password"} required value={password} onChange={e=>setPassword(e.target.value)}/></div><button disabled={busy}>{busy?"Bitte warten …":mode==="signup"?"Account anlegen":"Anmelden"}</button>{mode==="signup"&&<button type="button" className="secondary" disabled={busy} onClick={resend}>Bestätigungsmail erneut senden</button>}{message&&<p className="note">{message}</p>}</form></section><SiteFooter/></main>
}
