import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";

export default function PrivacyPage() {
  return <main className="shell legal-page"><nav className="nav"><Link className="brand" href="/">AI MUSIC <em>REBELS</em></Link><Link href="/">← Zur Startseite</Link></nav><article className="legal-card">
    <div className="legal-copy de-copy"><div className="eyebrow">Rechtliches</div><h1>Datenschutzerklärung</h1><p className="note">Stand: 02.09.2026</p><h2>1. Verantwortlicher</h2><p>Michael Jobst<br />Waldweg 3, 91171 Greding, Deutschland<br />E-Mail: jobst67@gmail.com<br />Telefon: 0160 4589605</p>
    <h2>2. Verarbeitete Daten</h2><p>Beim Betrieb von AI Music Rebels können insbesondere technische Verbindungs- und Protokolldaten, Kontodaten wie E-Mail-Adresse und Authentifizierungsinformationen, Profilangaben, hochgeladene Bilder, Titel-, Video- und Plattformlinks, Nutzungsdaten sowie Zahlungs- und Transaktionsinformationen verarbeitet werden. Zahlungsdaten selbst werden von Stripe verarbeitet; wir erhalten nur die für die Abonnementverwaltung erforderlichen Status- und Referenzdaten.</p>
    <h2>3. Zwecke und Rechtsgrundlagen</h2><ul><li>Bereitstellung der Seite, Registrierung, Profilverwaltung und Vertragserfüllung: Art. 6 Abs. 1 lit. b DSGVO.</li><li>Zahlungsabwicklung und gesetzliche Aufbewahrung: Art. 6 Abs. 1 lit. b und lit. c DSGVO.</li><li>IT-Sicherheit, Fehleranalyse, Missbrauchsabwehr und technische Stabilität: Art. 6 Abs. 1 lit. f DSGVO.</li><li>Optionale Erinnerungen zur Reaktivierung nach Ablauf eines Abonnements: Ihre Einwilligung bzw. Auswahl im Account, Art. 6 Abs. 1 lit. a DSGVO. Die Auswahl kann jederzeit im Account widerrufen werden.</li></ul>
    <h2>4. Empfänger und eingesetzte Dienste</h2><p>Für einzelne Funktionen setzen wir Auftragsverarbeiter und technische Dienstleister ein: Vercel für Hosting und Auslieferung, Supabase für Datenbank, Authentifizierung und Dateispeicher, Stripe für die Zahlungsabwicklung sowie Resend für den Versand von Transaktions- und Benachrichtigungs-E-Mails. Bei der Nutzung externer Links oder eingebetteter Inhalte (z. B. YouTube, Spotify oder Suno) gelten zusätzlich die Datenschutzbestimmungen der jeweiligen Plattform. Die Einbindung wird erst beim Aufruf der jeweiligen Inhalte oder Links ausgelöst.</p>
    <h2>5. Speicherdauer</h2><p>Kontodaten und Profildaten speichern wir für die Dauer des Nutzerkontos und, soweit erforderlich, für die Vertragsabwicklung. Nach einem abgelaufenen Abonnement bleiben Profildaten als nichtöffentliche Basisprofil-Daten gespeichert, damit der Nutzer den Kanal reaktivieren kann. Ein Nutzer kann die Löschung seines Kontos per E-Mail anfordern, soweit keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p>
    <h2>6. Ihre Rechte</h2><p>Sie haben nach Maßgabe der DSGVO insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit sowie Widerspruch gegen bestimmte Verarbeitungen. Eine erteilte Einwilligung kann jederzeit mit Wirkung für die Zukunft widerrufen werden. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p>
    <h2>7. Kontakt</h2><p>Datenschutzanfragen richten Sie bitte an jobst67@gmail.com.</p></div>
    <div className="legal-copy en-copy"><div className="eyebrow">Legal</div><h1>Privacy policy</h1><p className="note">Effective 2 September 2026</p><h2>1. Controller</h2><p>Michael Jobst<br />Waldweg 3, 91171 Greding, Germany<br />Email: jobst67@gmail.com<br />Phone: +49 160 4589605</p>
    <h2>2. Data processed</h2><p>When operating AI Music Rebels, we may process technical connection and log data, account details such as email and authentication information, profile information, uploaded images, track, video and platform links, usage data and payment or transaction information. Payment details themselves are processed by Stripe; we receive only status and reference data needed to manage subscriptions.</p>
    <h2>3. Purposes and legal bases</h2><ul><li>Provision of the service, registration, profile management and contract performance: Art. 6(1)(b) GDPR.</li><li>Payment processing and statutory record retention: Art. 6(1)(b) and (c) GDPR.</li><li>IT security, error analysis, abuse prevention and technical stability: Art. 6(1)(f) GDPR.</li><li>Optional reactivation reminders after an expired subscription: consent or account selection, Art. 6(1)(a) GDPR. This can be withdrawn at any time in the account.</li></ul>
    <h2>4. Recipients and services</h2><p>We use Vercel for hosting and delivery, Supabase for database, authentication and file storage, Stripe for payment processing and Resend for transactional and notification emails. When external links or embedded content such as YouTube, Spotify or Suno are used, the privacy policies of those platforms also apply. Their services are only contacted when the relevant content or link is opened.</p>
    <h2>5. Storage</h2><p>We retain account and profile data for the duration of the account and as necessary for contract performance. After a subscription ends, profile data remains stored as a private basic profile so the user can reactivate the channel. Users can request account deletion by email unless statutory retention duties apply.</p>
    <h2>6. Your rights</h2><p>Under the GDPR, you may have rights of access, rectification, erasure, restriction, portability and objection. Consent can be withdrawn at any time for the future. You also have the right to lodge a complaint with a data protection authority.</p>
    <h2>7. Contact</h2><p>Please send privacy requests to jobst67@gmail.com.</p></div>
  </article><SiteFooter /></main>;
}
