import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";

export default function ImprintPage() {
  return <main className="shell legal-page"><nav className="nav"><Link className="brand" href="/">AI MUSIC <em>REBELS</em></Link><Link href="/">← Zur Startseite</Link></nav><article className="legal-card">
    <div className="legal-copy de-copy"><div className="eyebrow">Rechtliches</div><h1>Impressum</h1><p className="note">Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG) · Stand: 02.09.2026</p><h2>Verantwortlich</h2><p>Michael Jobst<br />Waldweg 3<br />91171 Greding<br />Deutschland</p><h2>Kontakt</h2><p>Telefon: 0160 4589605<br />E-Mail: jobst67@gmail.com</p><h2>Umsatzsteuer</h2><p>Kleinunternehmer im Sinne des § 19 UStG. Gemäß § 19 UStG wird keine Umsatzsteuer erhoben.</p><h2>Verbraucherstreitbeilegung</h2><p>Wir sind weder verpflichtet noch bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><h2>Hinweis zu Drittplattformen</h2><p>AI Music Rebels ist ein unabhängiges Profil- und Linkangebot. Es besteht keine gesellschaftsrechtliche, geschäftliche oder sonstige offizielle Verbindung zu Suno, Spotify, YouTube oder anderen verlinkten Plattformen. Bezeichnungen und Marken Dritter verbleiben bei ihren jeweiligen Rechteinhabern.</p></div>
    <div className="legal-copy en-copy"><div className="eyebrow">Legal</div><h1>Legal notice</h1><p className="note">Information pursuant to section 5 German Digital Services Act · effective 2 September 2026</p><h2>Responsible person</h2><p>Michael Jobst<br />Waldweg 3<br />91171 Greding<br />Germany</p><h2>Contact</h2><p>Phone: +49 160 4589605<br />Email: jobst67@gmail.com</p><h2>VAT</h2><p>Small business pursuant to section 19 UStG. VAT is not charged.</p><h2>Consumer dispute resolution</h2><p>We are neither obliged nor willing to take part in dispute-resolution proceedings before a consumer arbitration board.</p><h2>Third-party services</h2><p>AI Music Rebels is an independent profile and link service. It has no official affiliation with Suno, Spotify, YouTube or other linked platforms. Third-party names and trademarks belong to their respective owners.</p></div>
  </article><SiteFooter /></main>;
}
